version: '3.7'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "SqlServerP4"
    ports:
      - "1433:1433"
    volumes:
      - ./db:/docker-entrypoint-initdb.d

